
[build]
    functions = "functions/"

[[redirects]]
  from = '/v1/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/v1/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"