
[build]
    functions = "functions/"

[[redirects]]
  from = '/v1/*'
  to = '/.netlify/functions/:splat'
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]  
  for = "/v1/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"